source 'https://rubygems.org'

gem "puma"

gem 'rails', '4.1.6'
gem "mongoid", "4.0.0"

group :development do
  gem "railroady"
end

group :development, :test do
  gem "rspec-rails", "~> 3.0.0"
  gem "capybara"
  gem "capybara-screenshot"
  gem "poltergeist"
  gem "factory_girl"
  gem "database_cleaner"
end
